#!/usr/bin/php
<?php
##############################
######  DEAMON SECTION  ######
##############################
require_once '/usr/local/emhttp/plugins/ipmi/include/ipmi_options.php';
require_once '/usr/local/emhttp/plugins/ipmi/include/ipmi_settings_fan.php';
require_once '/usr/local/emhttp/plugins/ipmi/include/ipmi_drives.php';
require_once '/usr/local/emhttp/plugins/dynamix/include/Helpers.php';

extract(parse_plugin_cfg('dynamix',true));
$debug = FALSE;

set_time_limit(0);
$prog     = pathinfo(__FILE__, PATHINFO_FILENAME);
$lockfile = "/var/run/{$prog}.pid";
$log      = '/var/log/ipmifan';
$service  = __FILE__;
openlog($prog, LOG_PID | LOG_PERROR, LOG_LOCAL0);

$usage = <<<EOF

Process settings in ipmi plugin fan config.
Control fans based on config values and [options].

Usage: $prog [options]

  -a, --auto       set fans to auto
      --full       set fans to full speed
    -n, --dryrun     output checks only; do not send fan commands
  -q, --quiet      suppress all messages
      --debug      turn on debugging
      --daemon     run in the background
      --help       display this help and exit
      --quit       stop daemon if running
      --version    output version information and exit


EOF;

$shortopts = 'adfqn';
$longopts = [
    'auto',
    'daemon',
    'dryrun',
    'debug',
    'full',
    'help',
    'quit',
    'quiet',
    'version'
];
$args = getopt($shortopts, $longopts);

if (array_key_exists('help', $args)) {
    echo $usage.PHP_EOL;
    exit(0);
}

if (array_key_exists('version', $args)) {
    echo 'IPMI Fan Control: 1.0'.PHP_EOL;
    exit(0);
}

$arga   = (array_key_exists('a', $args) || array_key_exists('auto', $args));
$argf   = (array_key_exists('full', $args));
$dryrun = (array_key_exists('n', $args) || array_key_exists('dryrun', $args));
$argq   = (array_key_exists('q', $args) || array_key_exists('quiet', $args));
$debug  = (array_key_exists('debug', $args));
$daemon = (array_key_exists('d', $args) || array_key_exists('daemon', $args));
$quit   = (array_key_exists('quit', $args));

$raw  = (empty($board_json)) ? '' : $board_json[$board]['raw'];

if(file_exists($lockfile)){
    $lock_pid = intval(file($lockfile, FILE_IGNORE_NEW_LINES)[0]);
    $pid_arg = escapeshellarg((string)$lock_pid);
    $pid_running = ($lock_pid > 0) ? preg_replace("/\s+/", "", shell_exec("ps -p $pid_arg | grep $pid_arg")) : '';
    if($pid_running){
        if($quit){
            fanlog('Stopping Fan Control');
            syslog(LOG_INFO, "killing daemon with PID [$lock_pid]");
            exec("kill $pid_arg");
            unlink($lockfile);
            autofan();
            exit(0);
        }else{
            echo "$prog is already running [$lock_pid]".PHP_EOL;
            exit(0);
        }
    }else{
        if($quit){
            echo "$lock_pid is not currently running".PHP_EOL;
            unlink($lockfile);
            exit(0);
        }else
            file_put_contents($lockfile, getmypid());
    }
}else{
    if($quit){
        echo "$prog not currently running".PHP_EOL;
        exit(0);
    }else
        file_put_contents($lockfile, getmypid());
}

if($arga){
        autofan();
        exit(0);
}

if($argf){
        fullfan();
        exit(0);
}

if (!$board_file_status) {
    $msg = "Your $board motherboard is not supported or setup yet";
    logger($msg, $argq);
    exit(1);
}

if($daemon){
    $daemon_args = [];
    if ($dryrun)
        $daemon_args[] = '--dryrun';
    if ($debug)
        $daemon_args[] = '--debug';
    if ($argq)
        $daemon_args[] = '--quiet';

    $daemon_cmd = 'php '.escapeshellarg($service);
    if (!empty($daemon_args))
        $daemon_cmd .= ' '.implode(' ', $daemon_args);

    exec($daemon_cmd.' 1>/dev/null '.($debug ? '' : '2>&1 ').'&');
    syslog(LOG_INFO, "process started. To terminate it, type: $prog --quit");
    exit(0);
}

#############################################
# ASRock
# ipmi-raw 00 3a 01 00 00 00 00 00 00 00 00
# ipmi-raw 00 3a 01 AA BB CC DD EE FF GG HH
# 00 = smartfan mode
# 01 - 64  = 1% - 100%
#############################################

#############################################
# ASRock Dual Socket
# ipmi-raw 00 3a 01 CPU_1_OVERRIDE CPU_1 REAR_1 FRONT_1 FRONT_2 FRONT_3
# ipmi-raw 00 3a 11 CPU_2_OVERRIDE CPU_2 REAR_2 FRONT_4
# ipmi-raw 00 3a 01 00 AA BB CC DD EE
# ipmi-raw 00 3a 11 00 AA BB CC
#############################################

#############################################
# ASRock 570
# ipmi-raw 00 3a d6 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
# ipmi-raw 00 3a d6 AA BB CC DD EE FF GG HH II JJ KK LL MM NN OO PP
# 00 = smartfan mode
# 01 - 64  = 1% - 100%
#############################################

#############################################
# Supermicro X10/X11
# ipmi-raw 00 30 70 66 01 00 64
# ipmi-raw 00 30 70 66 AA BB CC
#
# AA
# 00 - Get value
# 01 - Set value
#
# BB
# 00 - FAN 1/2/3/4 or CPU_FAN1/2
# 01 - FAN A or SYS_FAN1/2/3
#
# CC
# 00 to 64 - Set Speed (0-64)
#############################################

#############################################
# Supermicro X9
# ipmi-raw 00 30 91 5A 3 00 FF
# ipmi-raw 00 30 91 5A 3 BB CC
#
# BB
# 10 - FAN 1/2/3/4
# 11 - FAN A
#
# CC
# 00 to FF - Set Speed (0-255)
#############################################

#############################################
# Dell
# raw'    => '30 30 02 FF', # + value 01-64 for % FF is all or ID
#'auto'   => '30 30 01 00',
#'manual' => '30 30 01 01',
#'full'   => '30 30 02 FF 64',
# 01 - 64  = 1% - 100%
#############################################


#############################################
# Gigabyte Model for SW34-SP0
# raw    => '00 2e 10 0a 3c 00 40 01 CC BB', # + value 0-255 for speed and ID A0-A6
# auto   => '00 2e 10 0a 3c 00 40 00 00 00', 
# full   => '00 2e 10 0a 3c 00 40 01 FF FF',
#
# BB
# A0 - CPU_FAN
# A1 - SYS_FAN1
# A2 - SYS_FAN2
# A3 - SYS_FAN3
# A4 - SYS_FAN4
# A5 - SYS_FAN5
# A6 - SYS_FAN6
# FF - all fans 
#
# CC
# 00 to FF - Set Speed (0-255)
#
# Fan duty is a value from 1-255, where 1 is 0% and 255 is 100%. The command sets manual mode inline.
# No way to set individual fans to auto, but setting all fans to auto will override manual mode and set all fans to auto.
#############################################



##############################
###### FUNCTION SECTION ######
##############################

/* logger*/
function logger($msg, $quiet = false) {
    syslog(LOG_INFO, $msg);
    if (!$quiet)
        echo PHP_EOL.$msg.PHP_EOL;
}

/* logfile */
function fanlog($msg) {
    global $log;
    $msg = date('Y-m-d H:i:s').' '.$msg.PHP_EOL;
    file_put_contents($log,$msg,FILE_APPEND);
}

/* debug */
function debug($m){
  global $prog, $debug;
  if($debug){
    $STDERR = fopen('php://stderr', 'w+');
    fwrite($STDERR, $m.PHP_EOL);
    fclose($STDERR);
  }
}

/* auto fan */
function autofan() {
    global $board_json, $board, $board_model, $cmd_count, $fanopts, $dryrun;
    fanlog('Setting fans to auto');
    $cmd = '';
    switch($board) {
        case "ASRock":
        case "ASRockRack":
            //if board is ASRock or AsRockRack
            for($i = 0; $i <= $cmd_count; $i++){
                $board0 = ($i == 0) ? $board : $board.$i;
                $raw    = ipmi_hex_tokens($board_json[$board0]['raw']);
                $auto   = ipmi_hex_tokens($board_json[$board0]['auto']);
                $cmd   .= "ipmi-raw $raw $auto $fanopts 2>&1 >/dev/null &";
            }
            break;
        case "Supermicro":
            //if board is Supermicro
            $raw    = ipmi_hex_tokens($board_json[$board]['raw']);
            $auto = ipmi_hex_tokens($board_json[$board]['auto']);
            $mode = ipmi_hex_tokens(trim(shell_exec("ipmi-raw 00 30 45 00 | awk -F '45 00 ' '{print $2}'")));
            $cmd  = "ipmi-raw $auto $mode $fanopts 2>&1 >/dev/null &";
            break;
        case "Dell":
            //if board is Dell
            $raw = ipmi_hex_tokens($board_json[$board]['raw']);
            $auto = ipmi_hex_tokens($board_json[$board]['auto']);
            $cmd   = "ipmi-raw $auto $fanopts 2>&1 >/dev/null &";
            break;
        case "Giga":
            //if board is Giga
            $auto = ipmi_hex_tokens($board_json[$board]['auto']);
            $cmd  = "ipmi-raw $auto $fanopts 2>&1 >/dev/null &";
            break;
    }
    if ($dryrun) {
        fanlog('[DRYRUN] Skipping autofan command');
        debug('[DRYRUN] autofan cmd: '.$cmd);
    } else {
        shell_exec($cmd);
    }
}

/* manual fan */
function manualfan() {
    global $board_json, $board, $board_model, $cmd_count, $fanopts, $dryrun;
    fanlog('Setting fans to manual');
    $cmd = '';
    switch($board) {
        case "ASRock":
        case "ASRockRack":
            //if board is ASRock or AsRockRack
            for($i = 0; $i <= $cmd_count; $i++){
                $board0 = ($i == 0) ? $board : $board.$i;
                $raw    = ipmi_hex_tokens($board_json[$board0]['raw']);
                $auto   = ipmi_hex_tokens($board_json[$board0]['auto']);
                $cmd   .= "ipmi-raw $raw $auto $fanopts 2>&1 >/dev/null &";
            }
            break;
        case "Supermicro":
            //if board is Supermicro
            $raw    = ipmi_hex_tokens($board_json[$board]['raw']);
            $auto = ipmi_hex_tokens($board_json[$board]['auto']);
            $mode = ipmi_hex_tokens(trim(shell_exec("ipmi-raw 00 30 45 00 | awk -F '45 00 ' '{print $2}'")));
            $cmd  = "ipmi-raw $auto $mode $fanopts 2>&1 >/dev/null &";
            break;
        case "Dell":
            //if board is Dell
            $raw    = ipmi_hex_tokens($board_json[$board]['raw']);
            $manual = ipmi_hex_tokens($board_json[$board]['manual']);
            $cmd   = "ipmi-raw $manual $fanopts 2>&1 >/dev/null &";
            break;
    }
    if ($dryrun) {
        fanlog('[DRYRUN] Skipping manualfan command');
        debug('[DRYRUN] manualfan cmd: '.$cmd);
    } else {
        shell_exec($cmd);
    }
    sleep(10) ;
}

/* full speed fan */
function fullfan() {
    global $board_json, $board, $board_model, $cmd_count, $fanopts, $dryrun;
    fanlog('Setting fans to full speed');
    switch($board) {
        case "ASRock":
        case "ASRockRack":
            //if board is ASRock
            $cmd = '';
            for($i = 0; $i <= $cmd_count; $i++){
                $board0 = ($i == 0) ? $board : $board.$i;
                $raw    = ipmi_hex_tokens($board_json[$board0]['raw']);
                $full   = ipmi_hex_tokens($board_json[$board0]['full']);
                $cmd   .= "ipmi-raw $raw $full $fanopts 2>&1 >/dev/null &";
            }
            break;
        case "Supermicro":
            //if board is Supermicro
            $full = ipmi_hex_tokens($board_json[$board]['full']);
            $cmd  = "ipmi-raw $full $fanopts 2>&1 >/dev/null &";
            break;
        case "Dell":
            //if board is Dell
            $raw    = ipmi_hex_tokens($board_json[$board]['raw']);
            $full = ipmi_hex_tokens($board_json[$board]['full']);
            $cmd   = "ipmi-raw $full $fanopts 2>&1 >/dev/null &";
            break;
        case "Giga":
            //if board is Giga
            $full = ipmi_hex_tokens($board_json[$board]['full']);
            $cmd  = "ipmi-raw $full $fanopts 2>&1 >/dev/null &";
            break;
    }
    if ($dryrun) {
        fanlog('[DRYRUN] Skipping fullfan command');
        debug('[DRYRUN] fullfan cmd: '.$cmd);
    } else {
        echo shell_exec($cmd);
    }
    sleep(10);
}

/* get highest temp of hard drives */
function get_highest_temp(){
    global $hddignore;
    $ignore = array_flip(explode(',', $hddignore));

    //get UA devices
    $ua_json = '/var/state/unassigned.devices/hdd_temp.json';
    $ua_devs = file_exists($ua_json) ? json_decode(file_get_contents($ua_json), true) : [];

    //get all hard drives
    $disksini = parse_ini_file('/var/local/emhttp/disks.ini',true);
    $devsini = parse_ini_file('/var/local/emhttp/devs.ini',true);
    if ($devsini) $hdds = array_merge($disksini, $devsini); else $hdds = $disksini ;
    unset($hdds['flash']);

    $highest_temp = 0;
    foreach ($hdds as $hdd) {

        if (!array_key_exists($hdd['id'], $ignore)) {
            $temp = 0;
            if(array_key_exists('temp', $hdd))
                $temp = $hdd['temp'];
            elseif(!empty($ua_devs)){
                $ua_key = "/dev/".$hdd['device'];
                $temp = (array_key_exists($ua_key, $ua_devs)) ? $ua_devs[$ua_key]['temp'] : 0;
            }else{
                $device = isset($hdd['device']) ? preg_replace('/[^A-Za-z0-9]/', '', (string)$hdd['device']) : '';
                $temp = 0;
                if ($device !== '')
                    $temp = preg_replace("/\s+/", "", shell_exec('smartctl -A -n standby '.escapeshellarg('/dev/'.$device)." 2>/dev/null| grep -m 1 -i Temperature_Cel | awk '{print \$10}'"));
            }

            $highest_temp = ($temp > $highest_temp) ? $temp : $highest_temp;
        }
    }
    debug("Highest temp is {$highest_temp}ºC");
    return $highest_temp;
}

/* get highest temp of the hard drives assigned to a fan rule */
function get_highest_temp_for_fan($fan){
    global $fancfg, $hddignore;

    $include_key = "HDDINCLUDE_$fan";
    $include = isset($fancfg[$include_key]) ? trim((string)$fancfg[$include_key]) : '';
    if ($include === '')
        return get_highest_temp();

    $selected = array_flip(array_filter(explode(',', $include)));
    $ignore = array_flip(explode(',', $hddignore));
    $ua_json = '/var/state/unassigned.devices/hdd_temp.json';
    $ua_devs = file_exists($ua_json) ? json_decode(file_get_contents($ua_json), true) : [];
    $disksini = parse_ini_file('/var/local/emhttp/disks.ini',true);
    $devsini = parse_ini_file('/var/local/emhttp/devs.ini',true);
    if ($devsini) $hdds = array_merge($disksini, $devsini); else $hdds = $disksini ;
    unset($hdds['flash']);

    $highest_temp = 0;
    foreach ($hdds as $hdd) {
        if (!isset($hdd['id']) || !array_key_exists($hdd['id'], $selected) || array_key_exists($hdd['id'], $ignore))
            continue;

        $temp = 0;
        if(array_key_exists('temp', $hdd))
            $temp = $hdd['temp'];
        elseif(!empty($ua_devs)){
            $ua_key = "/dev/".$hdd['device'];
            $temp = (array_key_exists($ua_key, $ua_devs)) ? $ua_devs[$ua_key]['temp'] : 0;
        }

        if(is_numeric($temp))
            $highest_temp = ($temp > $highest_temp) ? $temp : $highest_temp;
    }
    debug("Highest temp for {$fan} is {$highest_temp}ºC");
    return $highest_temp;
}

/* get fan and temp sensors */
function ipmi_fan_sensors() {
    global $ipmi, $fanopts, $hdd_temp;

    // return empty array if no ipmi detected or network options
    if(!$ipmi && empty($fanopts))
        return [];

    $cmd = "/usr/sbin/ipmi-sensors --comma-separated-output --no-header-output --interpret-oem-data $fanopts 2>/dev/null";
    $return_var=null ;
    exec($cmd, $output, $return_var);

    // return empty array if error
    if($return_var)
        return [];

    // add hard drive temp as a sensor
    $output[] = "99,HDD Temperature,Temperature, $hdd_temp,C,Ok";

    // key names for ipmi sensors output
    $keys = ['ID', 'Name', 'Type', 'Reading', 'Units', 'Event'];
    $sensors = [];

    foreach($output as $line){

    /// add sensor keys as keys to ipmi sensor output
        $sensor_raw = explode(",", $line);
        $size_raw = sizeof($sensor_raw);
        $sensor = ($size_raw < 6) ? []: array_combine($keys, array_slice($sensor_raw,0,6,true));

        if ($sensor['Type'] === 'Temperature' || $sensor['Type'] === 'Fan')
            $sensors[$sensor['ID']] = $sensor;
    }
    return $sensors; // sensor readings
    unset($sensors);
}

function configured_fan_groups($board0, $fans){
    global $fancfg;

    $groups = [];
    $configured_fan_groups = isset($fancfg['FANGROUPS']) ? array_filter(array_map('trim', explode(',', $fancfg['FANGROUPS']))) : [];
    foreach($configured_fan_groups as $group){
        $targets = [];
        $selected = isset($fancfg["FANS_$group"]) ? array_filter(array_map('trim', explode(',', $fancfg["FANS_$group"]))) : [];
        foreach($selected as $fan){
            if(isset($fans[$fan]))
                $targets[$fan] = $fans[$fan];
        }
        $sensors_selected = isset($fancfg["SENSORS_$group"]) ? array_filter(array_map('trim', explode(',', $fancfg["SENSORS_$group"]))) : [];
        if(!empty($targets) && !empty($sensors_selected))
            $groups[] = ['name' => $group, 'targets' => collapse_selected_fans_by_target($board0, $targets), 'sensors' => $sensors_selected];
    }

    if(!empty($groups))
        return $groups;

    foreach($fans as $fan => $value){
        $fan_enabled = !isset($fancfg["FANENABLE_$fan"]) || strval($fancfg["FANENABLE_$fan"]) !== '0';
        if($fan_enabled && isset($fancfg["TEMP_$fan"]) && $fancfg["TEMP_$fan"] !== '')
            $groups[] = ['name' => $fan, 'targets' => [$fan => $value], 'sensors' => [$fancfg["TEMP_$fan"]]];
    }
    return $groups;
}

function collapse_selected_fans_by_target($board0, $targets){
    $by_target = [];
    foreach($targets as $fan => $value){
        $key = $board0.':'.$value;
        if(!isset($by_target[$key]))
            $by_target[$key] = [];
        $by_target[$key][$fan] = $value;
    }

    $collapsed = [];
    foreach($by_target as $key => $target_fans){
        if(count($target_fans) > 1)
            fanlog('Detected duplicate raw target / shared channel for selected fan group: '.implode(',', array_keys($target_fans)).' -> '.$key);
        foreach($target_fans as $fan => $value)
            $collapsed[$fan] = $value;
    }
    return $collapsed;
}

function group_sensor_reading($group, &$sensors){
    $highest = -1;
    $highest_sensor = null;
    foreach($group['sensors'] as $temp){
        if(!isset($sensors[$temp]))
            continue;
        $reading = floatval($sensors[$temp]['Reading']);
        if ($temp == "99") {
            $reading = floatval(get_highest_temp_for_fan($group['name']));
            $sensors['99']['Reading'] = $reading;
        }
        if($reading > $highest){
            $highest = $reading;
            $highest_sensor = $temp;
        }
    }
    return [$highest_sensor, max(0, $highest)];
}

function group_pwm($group, &$sensors){
    global $fancfg, $range;

    list($temp, $reading) = group_sensor_reading($group, $sensors);
    if($temp === null)
        return ['pwm' => '00', 'pct' => 0, 'name' => 'No sensor', 'reading' => 0];

    $templo  = isset($fancfg["TEMPLO_{$group['name']}"]) ? intval($fancfg["TEMPLO_{$group['name']}"]) : 30;
    $temphi  = isset($fancfg["TEMPHI_{$group['name']}"]) ? intval($fancfg["TEMPHI_{$group['name']}"]) : 45;
    $fanmin  = isset($fancfg["FANMIN_{$group['name']}"]) ? intval($fancfg["FANMIN_{$group['name']}"]) : 16;
    $fanmax  = isset($fancfg["FANMAX_{$group['name']}"]) ? intval($fancfg["FANMAX_{$group['name']}"]) : $range;
    $temploo = isset($fancfg["TEMPLOO_{$group['name']}"]) ? intval($fancfg["TEMPLOO_{$group['name']}"]) : 30;
    $temphio = isset($fancfg["TEMPHIO_{$group['name']}"]) ? intval($fancfg["TEMPHIO_{$group['name']}"]) : 45;
    $fanmino = isset($fancfg["FANMINO_{$group['name']}"]) ? intval($fancfg["FANMINO_{$group['name']}"]) : 16;
    $fanmaxo = isset($fancfg["FANMAXO_{$group['name']}"]) ? intval($fancfg["FANMAXO_{$group['name']}"]) : $range;
    $name = htmlspecialchars($sensors[$temp]['Name']);
    $use_override = false;

    if($temp == "99" && $reading <= 0 && isset($fancfg["TEMPHDD_{$group['name']}"]) && $fancfg["TEMPHDD_{$group['name']}"] != 0){
        $temp = $fancfg["TEMPHDD_{$group['name']}"];
        $reading = floatval($sensors[$temp]['Reading']);
        $name = "HDD Spundown using ".htmlspecialchars($sensors[$temp]['Name']);
        $use_override = true;
    }

    $lo = $use_override ? $temploo : $templo;
    $hi = $use_override ? $temphio : $temphi;
    $min = $use_override ? $fanmino : $fanmin;
    $max = $use_override ? $fanmaxo : $fanmax;

    if($reading <= $lo){
        $pct = 0;
        $pwm = 1;
    }elseif($reading >= $hi){
        $pct = 1;
        $pwm = $range;
    }else{
        $pct = ($reading-$lo)/($hi-$lo)*($max-$min)/$range + $min/$range;
        $pwm = round(($pct)*($range/4))*4;
    }
    if($pwm <= $min){
        $pwm = $min;
        $pct = $min/$range;
    }
    if($pwm >= $max){
        $pwm = $max;
        $pct = $max/$range;
    }
    if($range == 255)
        $pwm = dechex($pwm);
    $pwm = str_pad($pwm, 2, '0', STR_PAD_LEFT);
    return ['pwm' => $pwm, 'pct' => $pct, 'name' => $name, 'reading' => $reading];
}

##############################
#####  PROGRAM SECTION  ######
##############################

$MD5          = md5_file($fancfg_file);
$hdd_temp     = get_highest_temp();
$sensors      = ipmi_fan_sensors();
$ipmipoll     = ($fanpoll <= $hddpoll) ? $fanpoll : $hddpoll;
$fan_count    = $fanpoll * 10;
$hdd_count    = $hddpoll * 10;
$curent_hex   = '';
$current_hex2 = '';
$current_pwm_giga = [];
$current_pwm_by_target = [];

fanlog('Starting Fan Control');
fanlog("Board: $board Board Model: $board_model");
if($dryrun){
    fanlog('Dry run mode enabled: checks will run, fan commands will not execute');
}

if($board == 'Supermicro'){
    fanlog("SM Board selection: $smboard_model");
    if($dryrun)
        fanlog('[DRYRUN] Skipping startup fullfan for Supermicro');
    else
        fullfan();
}

if($board == 'Dell'){
    if($dryrun)
        fanlog('[DRYRUN] Skipping startup manualfan for Dell');
    else
        manualfan();
}

while(TRUE){ while(TRUE){
####  DO YOUR STUFF HERE  ####

    /* Refresh hdds and hdd temp if hdd poll time is expired */
    if ($hdd_count <= 0) {
        $hdd_count = $hddpoll * 10;
        $hdd_temp  = get_highest_temp();
        $sensors['99']['Reading'] = $hdd_temp;
    }
    /* Get sensor info if fan sensor poll time is expired */
    if ($fan_count <= 0) {
        $fan_count = $fanpoll * 10;
        $sensors = ipmi_fan_sensors();
    }

    for($i = 0; $i <= $cmd_count; $i++){
        $board0 = ($i == 0) ? $board : $board.$i;
        $raw    = ipmi_hex_tokens($board_json[$board0]['raw']);
        $fans   = $board_json[$board0]['fans'];
        $hex    = '';
        $msg    = 'Fan:Temp';
        $cmd    = '';
        $exec   = false;
        $fan_count  = 0;
        $pending_pwm_by_target = [];
        $max_pwm_by_target = [];
       # var_dump($fans,$raw) ;

        foreach(configured_fan_groups($board0, $fans) as $group){
            $group_result = group_pwm($group, $sensors);
            $pwm = ipmi_hex_tokens($group_result['pwm']);
            $pct = $group_result['pct'];
            $reading = $group_result['reading'];
            $name = $group_result['name'];
            $pct_label = str_pad(round($pct*100), 2, ' ', STR_PAD_LEFT);
            if ($reading <= 0) $mytemp = "Spundown" ; else $mytemp = str_replace([" ","&#8201;&#176;"],["",""],my_temp($reading));
            $msg .= ", {$group['name']}({$pct_label}%):".str_replace('Temperature','Temp',$name)."($mytemp)";

            foreach($group['targets'] as $target_fan => $value){
                $value = ipmi_hex_tokens($value);
                switch($board) {
                case "ASRock":
                case "ASRockRack":
                    switch($board_model) {
                        case 'EP2C612 WS':
                            $hex .= " $pwm";
                            break;
                        default:
                            if($cmd_count !== 0 && $fan_count == 0){
                                if($pwm == '00'){
                                    $hex .= ' 00 00';
                                }else{
                                    $hex .= " 01 $pwm";
                                }
                            }else{
                                $hex .= " $pwm";
                            }
                            break;
                    }
                    break;
                case "Supermicro":
                    $target_key = $board0.':'.$value;
                    $pwm_numeric = ($range == 255) ? hexdec($pwm) : intval($pwm);
                    if(!isset($max_pwm_by_target[$target_key]))
                        $max_pwm_by_target[$target_key] = $pwm_numeric;
                    else
                        $max_pwm_by_target[$target_key] = max($max_pwm_by_target[$target_key], $pwm_numeric);
                    if(!isset($pending_pwm_by_target[$target_key]) || $pwm_numeric >= $max_pwm_by_target[$target_key]){
                        $pending_pwm_by_target[$target_key] = [
                            'value' => $value,
                            'pwm' => $pwm,
                        ];
                    }
                    break;
                case "Dell":
                    if(($value == '00' || $value == '10') && $current_pwm !== $pwm && $pwm !== '00'){
                        $cmd = "ipmi-raw $raw $pwm $fanopts 2>&1; ";
                        $current_pwm  = $pwm;
                        $exec = true;
                    }
                    break;
                case "Giga":
                    $giga_key = $board0.':'.$value;
                    if(!isset($current_pwm_giga[$giga_key]))
                        $current_pwm_giga[$giga_key] = '';
                    if($current_pwm_giga[$giga_key] !== $pwm && $pwm !== '00'){
                        $cmd .= "ipmi-raw $raw $pwm $value $fanopts 2>&1; ";
                        $current_pwm_giga[$giga_key] = $pwm;
                        $exec = true;
                    }
                    break;
                }
                $fan_count++;
            }
        }
        if($board === 'Supermicro'){
            foreach($pending_pwm_by_target as $target_key => $target_pwm){
                $pwm = ipmi_hex_tokens($target_pwm['pwm']);
                $value = ipmi_hex_tokens($target_pwm['value']);
                if(!isset($current_pwm_by_target[$target_key]))
                    $current_pwm_by_target[$target_key] = '';
                if($current_pwm_by_target[$target_key] !== $pwm && $pwm !== '00'){
                    $cmd .= "ipmi-raw $raw $value $pwm $fanopts 2>&1; ";
                    $current_pwm_by_target[$target_key] = $pwm;
                    $exec = true;
                }
            }
        }
        switch($board) {
            case "ASRock":
            case "ASRockRack":
            //compare last value to new value for Asrock boards
            $hex_args = ipmi_hex_tokens($hex);
            $cmd_str = "ipmi-raw $raw $hex_args $fanopts 2>&1; ";

            if($i == 0){

                if($current_hex !== $hex){
                    $cmd = $cmd_str;

                    //set current value for next loop
                    $current_hex = $hex;
                    $exec = true;
                }
            }else{

                if($current_hex2 !== $hex){
                    $cmd = $cmd_str;

                    //set 2nd current value for next loop
                    $current_hex2 = $hex;
                    $exec = true;
                }
            }
            break;
        }

        // execute command if exec set, or log checks in dryrun mode
        if($dryrun){
            if($cmd)
                fanlog('[DRYRUN] '.$cmd);
            fanlog('[DRYRUN] '.$msg);
        } elseif($exec){
            shell_exec($cmd);
            #fanlog($cmd);
            if($debug)
                fanlog($cmd);

            //log changes
            fanlog($msg);
        }
    }
    /* print variable */
    $defined_vars = get_defined_vars();

    foreach (array('_GET','_POST','_COOKIE','_FILES','argv','argc','_SERVER') as $i)
        unset($defined_vars[$i]);

    if($debug)
        debug("\nDECLARED VARIABLES:\n".print_r($defined_vars, true));

    unset($defined_vars);

    $time1 = time();

    for ($i=0; $i < $ipmipoll ; $i++) {
        sleep(10);
        $fan_count = $fan_count - 10;
        $hdd_count = $hdd_count - 10;

        $MD5_new = md5_file($fancfg_file);
        if((file_exists($fancfg_file)) && ($MD5_new != $MD5)){
            $msg = 'fan control config file updated, reloading settings';
            $fancfg = parse_ini_file($fancfg_file);
            logger($msg, $argq);
            $MD5 = $MD5_new;
            fanlog($msg);
            break;
        }
    }
    debug("Sleep ".(time()-$time1)." seconds.");

######  END OF SECTION  ######
    };
};
?>
