#!/usr/bin/php
<?php
##############################
######  DEAMON SECTION  ######
##############################
require_once '/usr/local/emhttp/plugins/ipmi/include/ipmi_options.php';
require_once '/usr/local/emhttp/plugins/ipmi/include/ipmi_settings_fan.php';
$debug = FALSE;

set_time_limit(0);
$prog     = pathinfo(__FILE__, PATHINFO_FILENAME);
$prog2    = "ipmifan";
$lockfile = "/var/run/${prog2}.pid";
$log      = "/var/log/${prog2}";

$usage = <<<EOF

Check ASRock IPMI fan locations using ipmi-raw command and
create a json array for ipmifan script.

Usage: $prog [options]

  -f, --force      force start
      --debug      turn on debugging
      --help       display this help and exit
      --version    output version information and exit


EOF;

$shortopts = 'f';
$longopts = [
    'debug',
    'force',
    'help',
    'version'
];
$args = getopt($shortopts, $longopts);

if (array_key_exists('help', $args)) {
    echo $usage.PHP_EOL;
    exit(0);
}

if (array_key_exists('version', $args)) {
    echo 'IPMI 2 JSON: 1.0'.PHP_EOL;
    exit(0);
}

$debug  = (array_key_exists('debug', $args));

if(file_exists($lockfile) && !$force){
    $lock_pid = file($lockfile, FILE_IGNORE_NEW_LINES)[0];
    fanlog("Please stop ${prog2} [$lock_pid] then try again");
    exit(0);
}

if (!array_key_exists($board, $boards)){
    $msg = "Your $board motherboard is not supported yet";
    logger($msg, $argq);
    exit(1);
}

##############################
###### FUNCTION SECTION ######
##############################

/* logfile */
function fanlog($msg) {
    global $log;

    echo PHP_EOL.$msg.PHP_EOL;

    $msg = date('Y-m-d H:i:s').' '.$msg.PHP_EOL;
    file_put_contents($log,$msg,FILE_APPEND);
}

/* debug */
function debug($m){
  global $prog, $debug;
  if($debug){
    $STDERR = fopen('php://stderr', 'w+');
    fwrite($STDERR, $m.PHP_EOL);
    fclose($STDERR);
  }
}

/* get fan sensors */
function ipmi_sensors_fans() {
    global $ipmi, $fanopts;

    // return empty array if no ipmi detected or network options
    if(!$ipmi && empty($fanopts))
        return [];

    $cmd = "/usr/sbin/ipmi-sensors --comma-separated-output --no-header-output $fanopts 2>/dev/null";
    $return_var=null ;
    exec($cmd, $output, $return_var);

    // return empty array if error
    if($return_var)
        return [];

    // key names for ipmi sensors output
    $keys = ['ID', 'Name', 'Type', 'Reading', 'Units', 'Event'];
    $sensors = [];

    foreach($output as $line){

    /// add sensor keys as keys to ipmi sensor output
        $sensor_raw = explode(",", $line);
        $size_raw = sizeof($sensor_raw);
        $sensor = ($size_raw < 6) ? []: array_combine($keys, array_slice($sensor_raw,0,6,true));

        if ($sensor['Type'] == 'Fan')
            $sensors[$sensor['ID']] = $sensor;
    }
    return $sensors; // sensor readings
    unset($sensors);
}

function normalize_probe_fan_name($raw_name, $board, $index=1){
    $name = strtoupper(trim(str_replace(' ', '_', $raw_name)));
    if($board === 'Supermicro'){
        if(preg_match('/CPU_FAN([1-4])$/', $name, $m))
            return 'FAN'.$m[1];
        if(preg_match('/^FAN([1-4]|A|B)$/', $name, $m))
            return 'FAN'.$m[1];
        if(preg_match('/SYS_FAN([1-9])$/', $name, $m))
            return intval($m[1]) === 1 ? 'FANA' : 'FANB';
    }
    return preg_replace('/[^A-Z0-9_]/', '_', $name ?: ('FAN'.$index));
}

function sensor_rpm($sensor){
    if(!isset($sensor['Reading']) || !is_numeric($sensor['Reading']))
        return 0;
    return intval($sensor['Reading']);
}

function exclude_zero_rpm_fans($baseline, $tested=null){
    $present = [];
    foreach($baseline as $id => $fan){
        $base = sensor_rpm($fan);
        $test = ($tested !== null && isset($tested[$id])) ? sensor_rpm($tested[$id]) : $base;
        // Fans that continue to show 0 RPM during the test are treated as non-present.
        if($base > 0 || $test > 0)
            $present[$id] = $fan;
    }
    return $present;
}

function detect_fan_response($full_readings, $test_readings, $board){
    $responses = [];
    $present = exclude_zero_rpm_fans($full_readings, $test_readings);
    foreach($present as $id => $fan){
        if(!isset($test_readings[$id]))
            continue;
        $full = sensor_rpm($fan);
        $test = sensor_rpm($test_readings[$id]);
        if($full > 0 && ($full - $test) > 300){
            $name = normalize_probe_fan_name($fan['Name'], $board, count($responses) + 1);
            $responses[$name] = [
                'sensor_id' => $id,
                'sensor_name' => $fan['Name'],
                'full_rpm' => $full,
                'test_rpm' => $test,
            ];
        }
    }
    return $responses;
}

function probe_raw_command($board, $raw, $target, $pwm, $fanopts){
    $raw = ipmi_hex_tokens($raw);
    $target = ipmi_hex_tokens($target);
    $pwm = ipmi_hex_tokens($pwm);
    if($raw === '' || $target === '' || $pwm === '')
        return '';
    switch($board){
        case 'Supermicro':
            return "ipmi-raw $raw $target $pwm $fanopts 2>&1";
        case 'Giga':
            return "ipmi-raw $raw $pwm $target $fanopts 2>&1";
        default:
            return '';
    }
}

function probe_fan_channels($board, $source_board_json, $fanopts, $debug=false){
    $result = [];
    foreach($source_board_json as $board_key => $board_data){
        if(strpos($board_key, $board) !== 0 || !isset($board_data['fans']))
            continue;
        $raw = ipmi_hex_tokens($board_data['raw']);
        $full = ipmi_hex_tokens($board_data['full']);
        $auto = ipmi_hex_tokens($board_data['auto']);
        fanlog("Probing $board_key fan channels for shared/independent control and installed fans");
        if(!empty($full))
            shell_exec("ipmi-raw $raw $full $fanopts 2>&1");
        sleep(5);
        $fans_full = exclude_zero_rpm_fans(ipmi_sensors_fans());
        $detected_fan_map = [];
        $channel_to_fans = [];
        foreach($board_data['fans'] as $candidate_name => $target){
            $cmd = probe_raw_command($board, $raw, $target, '21', $fanopts);
            if($debug && $cmd)
                fanlog($cmd);
            if($cmd)
                shell_exec($cmd);
            sleep(5);
            $test_readings = ipmi_sensors_fans();
            $responses = detect_fan_response($fans_full, $test_readings, $board);
            $channel_to_fans[$target] = array_keys($responses);
            foreach($responses as $fan_name => $info){
                $detected_fan_map[$fan_name] = array_merge($info, ['target' => $target]);
            }
            $msg = empty($responses) ? 'no installed fan response' : implode(',', array_keys($responses));
            fanlog("Probe $board_key target $target: $msg");
            if(!empty($full))
                shell_exec("ipmi-raw $raw $full $fanopts 2>&1");
            sleep(2);
        }
        if(!empty($auto))
            shell_exec("ipmi-raw $raw $auto $fanopts 2>&1");
        $present_fans = [];
        foreach($detected_fan_map as $fan_name => $info)
            $present_fans[$fan_name] = $info['target'];
        $result[$board_key] = $board_data;
        $result[$board_key]['fans'] = $present_fans;
        $result[$board_key]['detected_fans'] = $detected_fan_map;
        $result[$board_key]['channel_to_fans'] = $channel_to_fans;
    }
    return $result;
}


##############################
#####  PROGRAM SECTION  ######
##############################


#############################################
# ASRock                                    #
# ipmi-raw 00 3a 01 00 00 00 00 00 00 00 00 #
# ipmi-raw 00 3a 01 AA BB CC DD EE FF GG HH #
# 00 = smartfan mode                        #
# 01 - 64  = 1% - 100%                      #
#############################################

#############################################
# ASRock Dual Socket
# ipmi-raw 00 3a 01 CPU_1_OVERRIDE CPU_1 REAR_1 FRONT_1 FRONT_2 FRONT_3
# ipmi-raw 00 3a 11 CPU_2_OVERRIDE CPU_2 REAR_2 FRONT_4
# ipmi-raw 00 3a 01 00 AA BB CC DD EE
# ipmi-raw 00 3a 11 00 AA BB CC
#############################################
#

####  DO YOUR STUFF HERE  ####


$lun   = '00';
$netfn = '3a';
$com   = '01';
$raw   = '00 3a 01';
$configured_board_json = $board_json;
$board_json = [];
$board_tmp = $board;

if ($cmd_count == 0){
    $fans_start = 0;
    $fans_count = 7;
    $auto  = '00 00 00 00 00 00 00 00';
    $full  = '64 64 64 64 64 64 64 64';
}else{
    $fans_start = 1;
    $fans_count = 5;
    $auto  = '00 00 00 00 00 00';
    $full  = '01 64 64 64 64 64';
}

fanlog('Checking IPMI fan Locations...');


if(($board === 'Supermicro' || $board === 'Giga') && isset($configured_board_json[$board])){
    $board_json = probe_fan_channels($board, $configured_board_json, $fanopts, $debug);
    fanlog('Saving board configuration...');
    file_put_contents($board_file, json_encode($board_json,JSON_PRETTY_PRINT));
    debug("\nDECLARED VARIABLES:\n".print_r(get_defined_vars(), true));
    exit(0);
}

for($i = 0; $i <= $cmd_count; $i++){
    $fans   = [];
    if ($i !== 0){
        $fans_count = 3;
        $auto  = '00 00 00 00';
        $full  = '01 64 64 64';
    }

    $raw = ipmi_hex_tokens("${lun} ${netfn} ${i}1");

    // set fans to full speed and get readings
    $full = ipmi_hex_tokens($full);
    $cmd = "ipmi-raw $raw $full $fanopts 2>&1";

    if ($debug)
       fanlog($cmd);

    shell_exec($cmd);

    sleep(5);
    $fans_full = ipmi_sensors_fans();

// step through each raw command position
    for($ii = $fans_start; $ii <= $fans_count; $ii++){
        $msg  = 'none';
        $location = ($cmd_count < 1 ? ($ii+1) : $ii);
        $name = 'FAN_POS'.$location;

        // set postition in raw command to 1/3 and get readings
        $hex = ipmi_hex_tokens(substr_replace($full,'21',$ii*3,2));

        $cmd = "ipmi-raw $raw $hex $fanopts 2>&1";

        if ($debug)
            fanlog($cmd);

        shell_exec($cmd);

        sleep(5);
        $fans_1third = ipmi_sensors_fans();

        // check for fan speed changes
        foreach($fans_full as $fan){
            if($fan['Reading'] != 'N/A') {
                if(($fan['Reading']-$fans_1third[$fan['ID']]['Reading']) > 300) {
                    $name = $fan['Name'];
                    $msg  = $name.' 100%: '.$fan['Reading'].' 33%: '.$fans_1third[$fan['ID']]['Reading'];
                }
            }
        }
        unset($fans_1third);
        $fans[$name] = $i.'1';
        fanlog("Location $i-".$location.': '.$msg);
    }

    $auto = ipmi_hex_tokens($auto);
    $cmd = "ipmi-raw $raw $auto $fanopts 2>&1";

    if ($debug)
       fanlog($cmd);

    shell_exec($cmd);

    if ($i !== 0)
        $board_tmp = $board.$i;

    $board_json[$board_tmp] =
        [ 'raw'   => $raw,
          'auto'  => $auto,
          'full'  => $full,
          'fans'  => $fans
        ];

}

fanlog('Saving board configuration...');
file_put_contents($board_file, json_encode($board_json,JSON_PRETTY_PRINT));

/* print variable */
$defined_vars = get_defined_vars();

foreach (array("_GET","_POST","_COOKIE","_FILES","argv","argc","_SERVER") as $i)
    unset($defined_vars[$i]);

debug("\nDECLARED VARIABLES:\n".print_r($defined_vars, true));
unset($defined_vars);

######  END OF SECTION  ######
?>